name: Continuous Integration

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta
  workflow_dispatch:

jobs:
  lint-commits:
    name: 'Lint: Commits'
    uses: jrposada/github-actions/.github/workflows/conventional-commits.yml@v1

  release:
    name: Get version
    needs: [lint-commits]
    permissions:
      contents: write
      pull-requests: write
    uses: jrposada/github-actions/.github/workflows/semantic-release.yml@v1

  publish:
    name: Publish
    if: needs.release.outputs.published == 'true'
    needs: [release]
    uses: jrposada/github-actions/.github/workflows/npm-publish.yml@v1
    with:
      version: ${{ needs.release.outputs.version }}
    secrets:
      token: ${{ secrets.NPM_TOKEN }}
